- name: Preparing z.lua directory
  file:
    path: "{{ zlua_local_path }}"
    state: directory

- name: Cloning z.lua
  git:
    repo: "{{ zlua_git_repo }}"
    dest: "{{ zlua_local_path }}"

- name: Copying shell file
  template: src=zlua.bash dest="{{ path_shell_config }}/zlua.bash"
