- name: Prepare tmp directory
  ansible.builtin.tempfile:
    state: directory
    suffix: rustup
  register: rustup_tmp_dir

- name: Set rustup_script_path fact
  ansible.builtin.set_fact:
    rustup_script_path: "{{ rustup_tmp_dir.path }}/rustup-init.sh"

- name: Download rustup installer script
  ansible.builtin.get_url:
    url: "https://sh.rustup.rs"
    dest: "{{ rustup_script_path }}"
    mode: "0755"

- name: Run rustup installer script
  ansible.builtin.command: "{{ rustup_script_path }} -y --no-modify-path -c rust-analyzer,rust-src"
  changed_when: true

- name: Clean up build directory
  ansible.builtin.file:
    path: "{{ rustup_tmp_dir.path }}"
    state: absent
