- name: Install rust
  block:

    - name: Checking if rustup is available
      ansible.builtin.command: "{{ ansible_env.HOME }}/.cargo/bin/rustup -V"
      register: cmd_rustup_installed
      ignore_errors: True

    - name: Install rust
      import_tasks: install.yml
      when: cmd_rustup_installed.rc > 0

    - name: Update rust
      ansible.builtin.command: "rustup update"
      register: rustup_update_cmd_result
      changed_when:
        - "'info: downloading' in rustup_update_cmd_result.stdout"
      when: cmd_rustup_installed.rc == 0

  when: rust_perform_install is undefined
