- name: Copy bashrc
  copy: src=_bashrc dest=~/.bashrc

- name: Copy profile
  template: src=_bash_profile dest=~/.bash_profile

- name: Create directory for modular configuration
  file:
    path: "{{ path_shell_config }}"
    state: directory
    mode: 0755

- name: Copy modular configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ path_shell_config }}/{{ item.path }}"
  with_filetree: shell/
  when: not "{{ item.path }}" is match('os_specific')

- name: Copy host-specific modular configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ path_shell_config }}/{{ item.path }}"
  with_filetree: shell/os_specific/
  when:
    - shell_additional_configs is defined
    - "shell_additional_configs is contains(item.path | basename)"
