- name: Create directory for local binaries
  file:
    path: "{{ path_local_bin }}"
    state: directory
    mode: 0755

- name: Create bashrc
  template: src=_bashrc dest=~/.bashrc

- name: Remove old shell config files
  file:
    dest: "{{ item }}"
    state: absent
  loop:
    - "~/.bash_profile"
    - "~/.profile"

- name: Create symlinks for other shell startup files
  file:
    src: "~/.bashrc"
    dest: "{{ item }}"
    state: link
  loop:
    - "~/.bash_profile"
    - "~/.profile"

- name: Installing shell scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ path_local_bin }}/{{ item.path }}"
    mode: "755"
  with_filetree: bin/

- name: Ensure clean state of modular configuration directory
  file:
    path: "{{ path_shell_config }}"
    state: "absent"

- name: Create directory for modular configuration
  file:
    path: "{{ path_shell_config }}"
    state: directory
    mode: 0755

- name: Copy modular configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ path_shell_config }}/{{ item.path }}"
  with_filetree: shell/
  when: not item.path is match('os_specific')

- name: Copy host-specific modular configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ path_shell_config }}/{{ item.path }}"
  with_filetree: shell/os_specific/
  when:
    - shell_extra_configs is defined
    - "shell_extra_configs is contains(item.path | basename)"
