- name: Create directory for local binaries
  ansible.builtin.file:
    path: "{{ path_local_bin }}"
    state: directory
    mode: "0755"

- name: Create bashrc
  ansible.builtin.template:
    src: _bashrc
    dest: ~/.bashrc
    mode: "0644"

- name: Create inputrc
  ansible.builtin.template:
    src: _inputrc
    dest: ~/.inputrc
    mode: "0644"

- name: Remove old shell config files
  ansible.builtin.file:
    dest: "{{ item }}"
    state: absent
  loop:
    - "~/.bash_profile"
    - "~/.profile"

- name: Create symlinks for other shell startup files
  ansible.builtin.file:
    src: "~/.bashrc"
    dest: "{{ item }}"
    state: link
  loop:
    - "~/.bash_profile"
    - "~/.profile"

- name: Installing shell scripts
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ path_local_bin }}/{{ item.path }}"
    mode: "0755"
  with_community.general.filetree: bin/

- name: Ensure clean state of modular configuration directory
  ansible.builtin.file:
    path: "{{ path_shell_config }}"
    state: "absent"

- name: Create directory for modular configuration
  ansible.builtin.file:
    path: "{{ path_shell_config }}"
    state: directory
    mode: "0755"

- name: Copy modular configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ path_shell_config }}/{{ item.path }}"
    mode: "0644"
  with_community.general.filetree: shell/
  when: not item.path is match('os_specific')

- name: Copy host-specific modular configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ path_shell_config }}/{{ item.path }}"
    mode: "0644"
  with_community.general.filetree: shell/os_specific/
  when:
    - shell_extra_configs is defined
    - "shell_extra_configs is contains(item.path | basename)"
