- name: Check pipx
  when: pipx_perform_install is undefined
  block:

    - name: Get current pipx version
      ansible.builtin.command: pipx --version
      register: cmd_pipx_installed
      ignore_errors: true
      changed_when: false

    - name: Remove pipx directory
      when:
        - cmd_pipx_installed.rc != 0
      block:

        - name: Remove existing pipx directory due to possible Python version mismatch
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/.local/pipx/"
            state: absent
        - name: Will install pipx
          ansible.builtin.set_fact:
            pipx_perform_install: true

    - name: Will install pipx
      ansible.builtin.set_fact:
        pipx_perform_install: true
      when:
        - (cmd_pipx_installed.stdout | trim ) != pipx_version

- name: Install pipx
  ansible.builtin.command: python3 -m pip install --user pipx=={{ pipx_version }}
  register: _pip_install
  when: pipx_perform_install is defined and pipx_perform_install
  changed_when:
    - "'Successfully installed' in _pip_install.stdout"

- name: Get currently installed packages
  ansible.builtin.command: pipx list --short
  register: cmd_pipx_pkgs_installed
  when: pipx_packages is truthy
  changed_when: false

- name: Get currently installed packages as Ansible dictionary
  ansible.builtin.set_fact:
    _pipx_packages_installed: |
      {{ cmd_pipx_pkgs_installed.stdout_lines | default([])
         | map('split', ' ')
         | community.general.dict
      }}

- name: Remove packages in wrong versions
  ansible.builtin.command: pipx uninstall {{ item.key }}
  loop: "{{ pipx_packages | dict2items }}"
  when:
    - item.key in _pipx_packages_installed
    - item.value != _pipx_packages_installed[item.key]
  changed_when: true

- name: Install missing packages
  ansible.builtin.command: |
    pipx install {{ item.key }}
    {%- if item.value != "*" -%}=={{ item.value }}{% endif %}
  loop: "{{ pipx_packages | dict2items }}"
  when: |
    item.key not in _pipx_packages_installed
    or (
        item.key in _pipx_packages_installed
        and item.value != _pipx_packages_installed[item.key]
    )
  changed_when: true

- name: Remove manually installed packages
  ansible.builtin.command: pipx uninstall {{ item.key }}
  loop: "{{ _pipx_packages_installed | dict2items }}"
  when:
    - item.key not in pipx_packages
  changed_when: true
