- name: Checking if lazygit is available
  ansible.builtin.command: lazygit --version
  register: cmd_lazygit_installed
  ignore_errors: true
  when: lazygit_perform_install is undefined
  changed_when: false

- name: Checking lazygit version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      lazygit --version | awk -F '[,=]' 'NR==1 {print $8}'
  register: cmd_lazygit_version
  when:
    - lazygit_perform_install is undefined
    - cmd_lazygit_installed.rc == 0
  changed_when: false

- name: Set lazygit_perform_install fact
  ansible.builtin.set_fact:
    lazygit_perform_install: true
  when:
    - lazygit_perform_install is undefined
    - cmd_lazygit_installed.rc != 0 or cmd_lazygit_version.stdout != lazygit_version

- name: Set up lazygit
  when: lazygit_perform_install is defined and lazygit_perform_install
  block:

    - name: Preparing tmp directory
      ansible.builtin.tempfile:
        state: directory
        suffix: lazygit
      register: lazygit_tmp_dir

    - name: Downloading lazygit archive
      ansible.builtin.get_url:
        url: "{{ lazygit_archive_url }}"
        dest: "{{ lazygit_tmp_dir.path }}/{{ lazygit_archive }}"
        mode: "0644"

    - name: Extracting lazygit archive
      ansible.builtin.unarchive:
        src: "{{ lazygit_tmp_dir.path }}/{{ lazygit_archive }}"
        dest: "{{ lazygit_tmp_dir.path }}"
        remote_src: true

    - name: Find extracted lazygit executable
      ansible.builtin.find:
        paths: "{{ lazygit_tmp_dir.path }}"
        patterns: "^lazygit$"
        recurse: true
        use_regex: true
      register: lazygit_find_results

    - name: Installing lazygit
      ansible.builtin.command: "cp {{ item.path }} {{ path_local_bin }}/lazygit"
      with_items: "{{ lazygit_find_results.files }}"
      changed_when: true

    - name: Ensuring correct executable permissions
      ansible.builtin.file:
        path: "{{ path_local_bin }}/lazygit"
        mode: "0775"

    - name: Clean up build directory
      ansible.builtin.file:
        path: "{{ lazygit_tmp_dir.path }}"
        state: absent
