starship_version: "0.41.3"
starship_vversion: "v{{ starship_version }}"
starship_archive: "starship-x86_64-unknown-linux-gnu.tar.gz"
starship_archive_url: "https://github.com/starship/starship/releases/download/{{ starship_vversion }}/{{ starship_archive }}"
