- name: Create target directory
  ansible.builtin.file:
    path: "{{ direnv_config_dir }}"
    state: directory
    mode: "0755"

- name: Copy direnvrc file
  ansible.builtin.copy:
    src: direnvrc
    dest: "{{ direnv_config_dir }}/direnvrc"
    mode: "0644"
