- name: Copy .npmrc file
  ansible.builtin.template:
    src: _npmrc
    dest: ~/.npmrc
    mode: "0664"

- name: Creating node symbolic link
  ansible.builtin.file:
    path: "{{ path_local_bin }}/node"
    src: "{{ path_target_node_binary }}"
    state: link
  when: path_target_node_binary is defined
