- name: Copy config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "~/{{ item | replace('_', '.', 1) }}"
    mode: "0644"
  loop:
    - _gitconfig
    - _gitignore_global
    - _gitallowed-signers
