- name: Ensuring vim autoload directory exists
  ansible.builtin.file:
    path: "{{ vim_dir }}/autoload"
    state: directory
    mode: "0775"

- name: Preparing directory for vim-plug git
  ansible.builtin.tempfile:
    state: directory
    suffix: vimplug
  register: vimplug_git_dir

- name: Cloning vimplug
  ansible.builtin.git: # noqa: latest
    repo: "{{ vimplug_git_repo }}"
    dest: "{{ vimplug_git_dir.path }}"
    depth: "1"

- name: Installing vimplug
  ansible.builtin.command: "cp {{ vimplug_git_dir.path }}/plug.vim {{ vim_dir }}/autoload/plug.vim"
  changed_when: true

- name: Clean up git directory
  ansible.builtin.file:
    path: "{{ vimplug_git_dir.path }}"
    state: absent
