- import_tasks: static_files.yml

- import_tasks: git_vim_plug.yml

- name: Installing vim plugins
  command: "vim +PlugInstall +qall"
  when: vim_install_plugins is defined and vim_install_plugins

- import_tasks: coc_plugins.yml
  when: vim_coc_extensions != ""
