- name: Prepare directories
  ansible.builtin.file:
    path: "{{ vim_dir }}/{{ item.path }}"
    state: directory
    mode: "0775"
  with_community.general.filetree: .
  when: item.state == 'directory'

- name: Copy modular configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ vim_dir }}/{{ item.path }}"
    mode: "0644"
  with_community.general.filetree: .
  when: item.state == 'file'
