fzf_version: "0.21.1"
fzf_archive: "fzf-{{ fzf_version }}-linux_amd64.tgz"
fzf_archive_url: "https://github.com/junegunn/fzf-bin/releases/download/{{ fzf_version }}/{{ fzf_archive }}"
fzf_git_repo: "https://github.com/junegunn/fzf.git"
