- name: Set up development environment
  hosts: all
  environment:
    PATH: "{{ path_local_bin }}:{{ ansible_env.PATH }}"
  roles:
    - role: group_hosts
      tags: ["always"]
    - role: shell
      tags: ["shell", "shell_config"]
    - role: ack
      tags: ["ack"]
    - role: ast-grep
      tags: ["ast-grep"]
    - role: bat
      tags: ["bat"]
    - role: direnv
      tags: ["direnv"]
    - role: fd
      tags: ["fd"]
    - role: fx
      tags: ["fx"]
    - role: fzf
      tags: ["fzf", "shell_config"]
    - role: git
      tags: ["git"]
    - role: ipython
      tags: ["ipython"]
    - role: lazygit
      tags: ["lazygit"]
    - role: nodejs
      tags: ["nodejs"]
    - role: nvim
      tags: ["nvim"]
    - role: pipx
      tags: ["pipx"]
    - role: pyenv
      tags: ["pyenv"]
    - role: ripgrep
      tags: ["ripgrep"]
    - role: R
      tags: ["R"]
    - role: rust
      tags: ["rust"]
    - role: starship
      tags: ["starship"]
    - role: tmux
      tags: ["tmux", "shell_config"]
    - role: vim
      tags: ["vim"]
    - role: wezterm
      tags: ["wezterm", "shell_config"]
    - role: xh
      tags: ["xh", "shell_config"]
    - role: z.lua
      tags: ["z.lua", "shell_config"]
