- name: Set up development environment
  hosts: all
  environment:
    PATH: "{{ path_local_bin }}:{{ ansible_env.PATH }}"
  roles:
    - role: group_hosts
      tags: ["always"]
    - role: shell
      tags: ["shell", "shell_config"]
    - role: ack
      tags: ["ack"]
    - role: bat
      tags: ["bat"]
    - role: direnv
      tags: ["direnv"]
    - role: fd
      tags: ["fd"]
    - role: fzf
      tags: ["fzf", "shell_config"]
    - role: git
      tags: ["git"]
    - role: ipython
      tags: ["ipython"]
    - role: nodejs
      tags: ["nodejs"]
    - role: R
      tags: ["R"]
    - role: starship
      tags: ["starship"]
    - role: tmux
      tags: ["tmux", "shell_config"]
    - role: vim
      tags: ["vim"]
    - role: z.lua
      tags: ["z.lua", "shell_config"]
