- name: Create target directory
  file: path=~/.ipython/profile_default state=directory mode=0755

- name: Copy default ipython profile file
  copy: src=ipython_config dest=~/.ipython/profile_default/ipython_config.py
