- name: Create target directory
  ansible.builtin.file:
    path: ~/.ipython/profile_default
    state: directory
    mode: "0755"

- name: Copy default ipython profile file
  ansible.builtin.copy:
    src: ipython_config
    dest: ~/.ipython/profile_default/ipython_config.py
    mode: "0664"
