bat_version: "0.15.4"
bat_vversion: "v{{ bat_version }}"
bat_archive: "bat-{{ bat_vversion }}-x86_64-unknown-linux-gnu.tar.gz"
bat_archive_url: "https://github.com/sharkdp/bat/releases/download/{{ bat_vversion }}/{{ bat_archive }}"
