ack_perform_install: no
bat_perform_install: no
fd_perform_install: no
starship_perform_install: no
lua_binary: lua53

shell_extra_vars:
  EDITOR: "vim"
  LANG: "pl_PL.UTF-8"
  LC_ALL: "pl_PL.UTF-8"
  CLICOLOR: "YES"
  GOPATH: "$HOME/go"

shell_extra_paths:
  - "{{ ansible_env.HOME }}/go/bin"
  - "{{ path_local_bin }}"
  - "{{ path_npm_global }}"
