ack_perform_install: no
bat_perform_install: no
fd_perform_install: no
pipx_perform_install: no
pipx_packages: {}
pyenv_perform_install: no
rust_perform_install: no
lua_binary: lua53
path_target_node_binary: "/usr/local/bin/node18"
lazygit_archive: "lazygit_{{ lazygit_version }}_freebsd_x86_64.tar.gz"
starship_perform_install: no
starship_archive: "starship-x86_64-unknown-freebsd.tar.gz"
tmux_default_terminal: "xterm-256color"
xh_perform_install: no

shell_extra_vars:
  LANG: "pl_PL.UTF-8"
  LC_ALL: "pl_PL.UTF-8"
  CLICOLOR: "YES"
  GOPATH: "$HOME/go"

shell_extra_paths:
  - "{{ ansible_env.HOME }}/go/bin"
  - "{{ path_local_bin }}"
  - "{{ path_npm_global }}/bin"

shell_extra_configs:
  - "bsd_alias.bash"
  - "git_completion.bash"
