ack_perform_install: no
bat_perform_install: no
fd_perform_install: no
lua_binary: lua53
path_target_node_binary: "/usr/local/bin/node14"
starship_archive: "starship-x86_64-unknown-freebsd.tar.gz"

shell_extra_vars:
  EDITOR: "vim"
  LANG: "pl_PL.UTF-8"
  LC_ALL: "pl_PL.UTF-8"
  CLICOLOR: "YES"
  GOPATH: "$HOME/go"

shell_extra_paths:
  - "{{ ansible_env.HOME }}/go/bin"
  - "{{ path_local_bin }}"
  - "{{ path_npm_global }}/bin"

shell_extra_configs:
  - "bsd_alias.bash"
