ack_perform_install: no
pipx_perform_install: no
shell_extra_vars:
  LANG: "pl_PL.UTF-8"
  LC_ALL: "pl_PL.UTF-8"
  BROWSER: "/usr/bin/firefox"
  GTK_IM_MODULE: "xim"
  GTK_USE_PORTAL: 1
  TEXMFHOME: "$HOME/.texmf"
  DEBEMAIL: "miroslaw-zalewski@o2.pl"
  DEBFULLNAME: "Mirosław Zalewski"

shell_extra_paths:
  - "{{ ansible_env.HOME }}/skrypty"
  - "{{ path_local_bin }}"
  - "{{ ansible_env.HOME }}/.cargo/bin"

shell_extra_configs:
  - "debian_alias.bash"

vim_coc_extensions: "coc-css coc-html coc-json coc-phpls coc-jedi coc-r-lsp coc-snippets coc-tsserver coc-yaml"
