ack_perform_install: false
git_email: mzalewsk@redhat.com
vim_coc_extensions: "coc-json coc-jedi coc-snippets coc-yaml"
nvim_lsps_exclude:
  - "intelephense"
  - "r_language_server"
  - "texlab"
pipx_perform_install: false
pipx_packages:
  crc-bonfire: "*"
  cookiecutter: "*"
  git-filter-repo: "*"
  jedi-language-server: "*"
  neovim-remote: "*"
  nox: "2025.5.1"
  poetry: "2.1.3"
  python-openstackclient: "*"
  reuse: "*"
  uv: "0.7.15"
  vmmgr: "0.1.0"

shell_extra_vars:
  BROWSER: "/usr/bin/google-chrome"
  VAGRANT_DEFAULT_PROVIDER: "libvirt"
  VMMGR_TEMPLATE_IMAGES_POOLS: "VirtualMachines"

shell_extra_paths:
  - "{{ path_local_bin }}"
  - "{{ ansible_env.HOME }}/.cargo/bin"

shell_extra_configs:
  - "00_source_etc_bashrc.bash"
