ack_perform_install: no
git_email: mzalewsk@redhat.com
vim_coc_extensions: "coc-json coc-jedi coc-snippets coc-yaml"
nvim_lsps_exclude:
  - "intelephense"
  - "r_language_server"
  - "texlab"
pipx_perform_install: no
pipx_packages:
  crc-bonfire: "*"
  cookiecutter: "*"
  git-filter-repo: "*"
  jedi-language-server: "*"
  neovim-remote: "*"
  nox: "2025.5.1"
  poetry: "2.1.3"
  python-openstackclient: "*"
  reuse: "*"
  uv: "0.6.17"

shell_extra_vars:
  BROWSER: "/usr/bin/google-chrome"
  VAGRANT_DEFAULT_PROVIDER: "libvirt"

shell_extra_paths:
  - "{{ path_local_bin }}"
  - "{{ ansible_env.HOME }}/.cargo/bin"

shell_extra_configs:
  - "00_source_etc_bashrc.bash"
