ack_perform_install: false
git_email: mzalewsk@redhat.com
vim_coc_extensions: "coc-json coc-jedi coc-snippets coc-yaml"
nvim_lsps_exclude:
  - "intelephense"
  - "texlab"
pipx_perform_install: false
pipx_packages:
  crc-bonfire: "*"
  cookiecutter: "*"
  git-filter-repo: "*"
  jedi-language-server: "*"
  neovim-remote: "*"
  nox: "2025.5.1"
  poetry: "2.1.4"
  python-openstackclient: "*"
  reuse: "*"
  uv: "0.7.15"
  vmmgr: "0.1.0"

pyenv_python_312_path: "{{ pyenv_local_path }}/versions/{{ pyenv_versions | select('match', '3\\.12') | last }}/bin/python3"
recreate_python_envs:
  - source_dir: "{{ path_sources }}/camayoc"
    venv_path: "{{ path_virtualenvs }}/camayoc"
    python_path: "{{ pyenv_python_312_path }}"
    postinstall_cmd: >
      uv sync --frozen --group dev --active &&
      pip install ipython pickleshare ipdb
  - source_dir: "{{ path_sources }}/discovery-ci"
    venv_path: "{{ path_virtualenvs }}/discovery-ci"
    python_path: "{{ pyenv_python_312_path }}"
    postinstall_cmd: >
      uv sync --frozen --group dev --active &&
      pip install ipython pickleshare ipdb
  - source_dir: "{{ path_sources }}/qpc"
    venv_path: "{{ path_virtualenvs }}/qpc"
    python_path: "{{ pyenv_python_312_path }}"
    postinstall_cmd: >
      uv sync --frozen --active &&
      pip install ipython pickleshare ipdb
  - source_dir: "{{ path_sources }}/quipucords"
    venv_path: "{{ path_virtualenvs }}/quipucords"
    python_path: "{{ pyenv_python_312_path }}"
    postinstall_cmd: >
      uv sync --frozen --group dev --active &&
      pip install ipython pickleshare ipdb
  - source_dir: "{{ path_sources }}/mirekdlugosz.com"
    venv_path: "{{ path_virtualenvs }}/mirekdlugosz.com"
    python_path: "{{ default_pyenv_python_path }}"
    postinstall_cmd: >
      pip install -U pip wheel polars &&
      pip install -r requirements.txt

shell_extra_vars:
  BROWSER: "/usr/bin/google-chrome"
  VAGRANT_DEFAULT_PROVIDER: "libvirt"
  VMMGR_TEMPLATE_IMAGES_POOLS: "VirtualMachines"

shell_extra_paths:
  - "{{ path_local_bin }}"
  - "{{ ansible_env.HOME }}/.cargo/bin"

shell_extra_configs:
  - "00_source_etc_bashrc.bash"
